### ISSUE TITLE
Close test or submit buffer

### ISSUE THREAD

**Issue by wukong4430** [ianding1/leetcode.vim#1]
Hey, I wonder how to close test or submit buffer..
Or how to switch to these buffers..  Thanks..

**Comment by ianding1** [comment]
Hi, 

The test/submission buffer are shown in a preview window. You can close the preview window with `ctrl-w z` or `:pclose`. The buffers are deleted when the window is closed. Therefore, you cannot switch to these buffers again after closing the preview window.

Vim requires that there is only at most one preview window at any time. Hence, when a new test/submission window is opened, the previous one is closed automatically.

By the way, there IS an approach that we keep the test/submission buffers instead of deleting them after closing the window. But if we accepted this approach, we would need to remember to delete those buffers manually, which could be an unnecessary burden.
