### ISSUE TITLE
File name problem

### ISSUE THREAD

**Issue by gu18168** [ianding1/leetcode.vim#10]
When I use `Rust` to solve problems, the  problem's file name will be a problem. For example, problem one's file name is `two-sum.rs`, but in rust, we use `_` instead of `-`. So I need to manually modify the file name to `two_sum.rs`, and if I want to test or submit, I must revise it again...

**Comment by gu18168** [comment]
Now, I changed the code privately. For example, In `leetcode.vim L.476 function! leetcode#TestSolution()`, I judge  `filetype` , if it's `rust`，I will use `tr(slug, '_', '-')` to avoid manually modifying the file name.

This is my expedient measure. I don't know if it is a good modification.

**Comment by ianding1** [comment]
Hi, I would like to know if using hyphens rather than underscores would cause real problems.

IMO, style checkers and autocompletion should be turned off when doing leetcode, since they're not available in the real interview, in which case, filenames won't be an issue.

But if it's bothering you, please let me know.

**Comment by ianding1** [comment]
Hi, I changed the file name style to snake case. I hope this could solve your problem. Enjoy 🎉
 
Related commit: 13f6fff014c4981d59d6832d1888e171ee2670c5

**Comment by gu18168** [comment]
Thank you very much. In my case, I want to do some unit test for myself, so I need a correct file name. Now it can work, thank you again.
