### ISSUE TITLE
Focus on the window split

### ISSUE THREAD

**Issue by mahdi-hosseini** [ianding1/leetcode.vim#11]
Thanks for creating this!

Would it be possible to make the plugin focus on the window split when we interact with plugin? Right now any action I take, I have to press extra keystrokes to switch to the window split created by your awesome plugin.

**Comment by ianding1** [comment]
Hi, in case I misunderstood, do you mean the behavior that the cursor is left at the original window after the running result window shows up?

I found it more convenient to keep the cursor unchanged, since most of the time i only glance at the result and close it immediately.

My personal preference is to use `<ctrl-w> z` to close the result window (since it's a preview) and `<alt-d>`/`<alt-u>` to scroll it while keeping the cursor in the original window with the help of [vim-preview](https://github.com/skywind3000/vim-preview).

**Comment by mahdi-hosseini** [comment]
@ianding1 Thank you for the tips, that addresses my concern!
