### ISSUE TITLE
Failed to run test and submit

### ISSUE THREAD

**Issue by crokobit** [ianding1/leetcode.vim#31]
After LeetCodeSubmit command:
```
error: 'NoneType' object is not subscriptable
```
After LeetCodeTest command:
```
Error detected while processing function leetcode#TestSolution[17]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 4 (python3-script-host):
error caught in request handler 'python_eval ['leetcode.get_problem("1")']':
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 165, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/crokobit/.vim/plugged/leetcode.vim/autoload/leetcode.py", line 246, in get_problem
    content = q['translatedContent'] or q['content']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jamak** [comment]
I also have this  issue, on macOS Catalina with vim 8.1 and the mostt recent version of leetcode.vim

**Comment by ywpkwon** [comment]
I also have this issue, on Ubuntu 18.04  with neovim v0.4.2

**Comment by ianding1** [comment]
It looks like that leetcode changed its API again. Investigating...

**Comment by ywpkwon** [comment]
Thanks for investigating. Why do they keep changing APIs...? :(

**Comment by ianding1** [comment]
It turns out that the code failed to detect when the session cookie is expired.

This commit should have fixed the problem: 8cb81b57ceb110918663ca8bc6dc3c87a511a3b5

Please let me know if it does not work.

**Comment by crokobit** [comment]
@ianding1 Still got same error.

**Comment by ianding1** [comment]
Hi, @crokobit  i noticed that in the error message the argument passed to `leetcode.get_problem` was `"1"` while it should have been a slug, for example, `"two-sum"`. So i'd like to know if the file name was modified.

Currently we guess the problem slug from the file name. For example, if the file name is `two-sum.c`, then we will assume that the problem is `two-sum`.

**Comment by crokobit** [comment]
@ianding1 Not sure what "the file name was modified." means. But the file name does be the same as the slug of that question. e.g. `two-sum.rb`

Tried the commit @Wilnath did by modify package code directly but still got the same result.

**Comment by Wilnath** [comment]
@crokobit Do new problems you download have the problem id before the name? something like `1.two_sum.cpp`. The problem I was having that @ianding1 described is the problem id getting sent instead of the slug.

I assumed that all new files get the problem id as a prefix but if that isn't the case my commit will definitely break things 😅

**Comment by crokobit** [comment]
@Wilnath  What I mentioned in the previous comment is wrong. My file name did have the prefix. like `1.two_sum.cpp`. But still got faile even with @Wilnath 's fix.

**Comment by ianding1** [comment]
It looks like that the file name change brought some troubles.

Thanks to @Wilnath for pointing out the cause.

To summarize what has happened, leetcode.vim used to create files in two formats, taking _TwoSum_ as example, `two_sum.c` and `two_sum.1234.c` where the latter is for a specific submission `1234`.

Recently leetcode.vim prepended the problem ID to the file name, so we have a new file name `1.two_sum.c`.

Unfortunately, leetcode.vim didn't modify other parts accordingly, such as testing and submission.

With this fix 4aaec9fd5c0b0dd8, the problem should be gone.

I'm ___very sorry___ for all the inconvenience and frustrations caused by this bug. I'll learn from it and pay attention to _breaking_ changes in the future.

I hope you enjoy and keep supporting leetcode.vim.

**Comment by crokobit** [comment]
@ianding1 It works! really thank you for your efforts in doing this amazing plugin! :)

**Comment by linweilin** [comment]
Still get the same error on WSL2 Ubuntu 22.04
```
Error detected while processing function leetcode#ListProblems[2]..<SNR>67_CheckSignIn[2]..leetcode#SignIn[1]..<SNR>67_LoadSessionCookie[6]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 4 (python3-script-host):
error caught in request handler 'python_eval ['leetcode.load_session_cookie("chrome")']':
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pynvim/plugin/script_host.py", line 171, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/home/william/.config/nvim/plugged/leetcode.vim/autoload/leetcode.py", line 168, in load_session_cookie
    session_cookie_raw = keyring.get_password('leetcode.vim', 'SESSION_COOKIE')
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/usr/lib/python3/dist-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt pac
kage if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```
